# Scratch: raw rivalry list scraped from Wikipedia's "List of NCAA college
# football rivalry games", (rivalry_name, school_a, school_b) using
# Wikipedia's school naming. Used once by build_rivalries.py to resolve
# against our teams table, then discarded -- not part of the shipped code.
RAW = [
    ("100 Miles of Hate", "Middle Tennessee", "Western Kentucky"),
    ("Air Force-Colorado State", "Air Force", "Colorado State"),
    ("Air Force-Hawaii", "Air Force", "Hawaii"),
    ("Akron-Kent State", "Akron", "Kent State"),
    ("Alabama-Clemson", "Alabama", "Clemson"),
    ("Alabama-Florida", "Alabama", "Florida"),
    ("Alabama-Georgia", "Alabama", "Georgia"),
    ("Alabama-Georgia Tech", "Alabama", "Georgia Tech"),
    ("Alabama-LSU", "Alabama", "LSU"),
    ("Alabama-Ole Miss", "Alabama", "Ole Miss"),
    ("Alabama-Penn State", "Alabama", "Penn State"),
    ("Apple Cup", "Washington", "Washington State"),
    ("Arch Rivalry", "Illinois", "Missouri"),
    ("Arizona-New Mexico", "Arizona", "New Mexico"),
    ("Arkansas-LSU", "Arkansas", "LSU"),
    ("Arkansas-Ole Miss", "Arkansas", "Ole Miss"),
    ("Arkansas-Texas", "Arkansas", "Texas"),
    ("Arkansas-Texas A&M", "Arkansas", "Texas A&M"),
    ("Arkansas-Texas Tech", "Arkansas", "Texas Tech"),
    ("Army-Navy Game", "Army", "Navy"),
    ("Army-Notre Dame", "Army", "Notre Dame"),
    ("Auburn-Clemson", "Auburn", "Clemson"),
    ("Auburn-Florida", "Auburn", "Florida"),
    ("Auburn-Georgia Tech", "Auburn", "Georgia Tech"),
    ("Auburn-Mississippi State", "Auburn", "Mississippi State"),
    ("Auburn-Ole Miss", "Auburn", "Ole Miss"),
    ("Auburn-Tennessee", "Auburn", "Tennessee"),
    ("Auburn-Tulane", "Auburn", "Tulane"),
    ("Backyard Brawl", "Pittsburgh", "West Virginia"),
    ("Ball State-Northern Illinois", "Ball State", "Northern Illinois"),
    ("Battle for Highway 82", "Alabama", "Mississippi State"),
    ("Battle for Nevada", "Nevada", "UNLV"),
    ("Battle for the Bell (Cincinnati-Miami)", "Cincinnati", "Miami (OH)"),
    ("Battle for the Bell (Marshall-Ohio)", "Marshall", "Ohio"),
    ("Battle for the Bell (Southern Miss-Tulane)", "Southern Miss", "Tulane"),
    ("Battle for the Belt", "South Alabama", "Troy"),
    ("Battle for the Bones", "Memphis", "UAB"),
    ("Battle for the Iron Skillet", "SMU", "TCU"),
    ("Battle for the Land Grant", "Michigan State", "Penn State"),
    ("Battle for the Ol' School Bell", "Jacksonville State", "Troy"),
    ("Battle for the Palladium", "Middle Tennessee", "Troy"),
    ("Battle for the Rag", "LSU", "Tulane"),
    ("Battle for the Valley", "Fresno State", "San José State"),
    ("Battle Line Rivalry", "Arkansas", "Missouri"),
    ("Battle of I-10", "New Mexico State", "UTEP"),
    ("Battle of the Blue Ridge", "James Madison", "Liberty"),
    ("Battle of the Brazos", "Baylor", "Texas A&M"),
    ("Battle of the Bricks", "Miami (OH)", "Ohio"),
    ("Battle of the Brothers", "Utah", "Utah State"),
    ("Battle of the Carolinas", "North Carolina", "South Carolina"),
    ("Battle on the Bayou", "Louisiana", "Louisiana-Monroe"),
    ("Baylor-Houston", "Baylor", "Houston"),
    ("Baylor-Rice", "Baylor", "Rice"),
    ("Baylor-Texas", "Baylor", "Texas"),
    ("Baylor-Texas Tech", "Baylor", "Texas Tech"),
    ("Bedlam Series", "Oklahoma", "Oklahoma State"),
    ("Big Game", "California", "Stanford"),
    ("Bill Walsh Legacy Game", "San José State", "Stanford"),
    ("Black and Blue Bowl", "Memphis", "Southern Miss"),
    ("Bluebonnet Battle", "Baylor", "TCU"),
    ("Boise State-Fresno State", "Boise State", "Fresno State"),
    ("Boise State-Nevada", "Boise State", "Nevada"),
    ("Border War (Colorado State-Wyoming)", "Colorado State", "Wyoming"),
    ("Border War (Kansas-Missouri)", "Kansas", "Missouri"),
    ("Boston College-Clemson", "Boston College", "Clemson"),
    ("Boston College-UMass", "Boston College", "UMass"),
    ("Boston College-Virginia Tech", "Boston College", "Virginia Tech"),
    ("Bowling Green-Kent State", "Bowling Green", "Kent State"),
    ("Bowling Green-Toledo", "Bowling Green", "Toledo"),
    ("Bridger's Battle", "Utah State", "Wyoming"),
    ("Buffalo-UMass", "Buffalo", "UMass"),
    ("BYU-Utah State", "BYU", "Utah State"),
    ("California-UCLA", "California", "UCLA"),
    ("California-USC", "California", "USC"),
    ("Central Michigan-Eastern Michigan", "Central Michigan", "Eastern Michigan"),
    ("Central Michigan-Western Michigan", "Central Michigan", "Western Michigan"),
    ("Centre-Kentucky", "Centre", "Kentucky"),
    ("Chicago-Michigan", "Chicago", "Michigan"),
    ("Chicago-Purdue", "Chicago", "Purdue"),
    ("Cincinnati-Louisville", "Cincinnati", "Louisville"),
    ("Cincinnati-Memphis", "Cincinnati", "Memphis"),
    ("Cincinnati-UCF", "Cincinnati", "UCF"),
    ("Cincinnati-West Virginia", "Cincinnati", "West Virginia"),
    ("Clean, Old-Fashioned Hate", "Georgia", "Georgia Tech"),
    ("Clemson-Florida State", "Clemson", "Florida State"),
    ("Clemson-Georgia", "Clemson", "Georgia"),
    ("Clemson-Georgia Tech", "Clemson", "Georgia Tech"),
    ("Coastal Carolina-Liberty", "Coastal Carolina", "Liberty"),
    ("Colorado-Kansas State", "Colorado", "Kansas State"),
    ("Colorado-Nebraska", "Colorado", "Nebraska"),
    ("Crab Bowl Classic", "Maryland", "Navy"),
    ("Deeper than Hate", "Appalachian State", "Georgia Southern"),
    ("Deep South's Oldest Rivalry", "Auburn", "Georgia"),
    ("Dick Tomey Legacy Game", "Hawaii", "San José State"),
    ("Duel in the Desert", "Arizona", "Arizona State"),
    ("Duke-Georgia Tech", "Duke", "Georgia Tech"),
    ("Duke-North Carolina", "Duke", "North Carolina"),
    ("Duke-NC State", "Duke", "NC State"),
    ("Duke-Virginia", "Duke", "Virginia"),
    ("Duke-Wake Forest", "Duke", "Wake Forest"),
    ("East Carolina-Marshall", "East Carolina", "Marshall"),
    ("East Carolina-NC State", "East Carolina", "NC State"),
    ("Egg Bowl", "Mississippi State", "Ole Miss"),
    ("Farmageddon", "Iowa State", "Kansas State"),
    ("Florida-Florida State", "Florida", "Florida State"),
    ("Florida-Georgia", "Florida", "Georgia"),
    ("Florida-Kentucky", "Florida", "Kentucky"),
    ("Florida-LSU", "Florida", "LSU"),
    ("Florida-Miami", "Florida", "Miami"),
    ("Florida-Tennessee", "Florida", "Tennessee"),
    ("Florida State-Miami", "Florida State", "Miami"),
    ("Florida State-Virginia", "Florida State", "Virginia"),
    ("Frank Leahy Memorial Bowl", "Boston College", "Notre Dame"),
    ("Fresno State-Hawaii", "Fresno State", "Hawaii"),
    ("Fresno State-San Diego State", "Fresno State", "San Diego State"),
    ("Friends of Coal Bowl", "Marshall", "West Virginia"),
    ("Georgia-South Carolina", "Georgia", "South Carolina"),
    ("Georgia-Tennessee", "Georgia", "Tennessee"),
    ("Georgia-Vanderbilt", "Georgia", "Vanderbilt"),
    ("Georgia Tech-Tennessee", "Georgia Tech", "Tennessee"),
    ("Georgia Tech-Vanderbilt", "Georgia Tech", "Vanderbilt"),
    ("Governors' Trophy Game", "Oregon", "Saint Mary's"),
    ("Green Line Rivalry", "Boston College", "Boston University"),
    ("Hawaii-Wyoming", "Hawaii", "Wyoming"),
    ("Holy War", "BYU", "Utah"),
    ("Houston-Rice", "Houston", "Rice"),
    ("Houston-SMU", "Houston", "SMU"),
    ("Houston-Texas Tech", "Houston", "Texas Tech"),
    ("I-35 Rivalry", "Texas State", "UTSA"),
    ("Illinois-Indiana", "Illinois", "Indiana"),
    ("Illinois-Iowa", "Illinois", "Iowa"),
    ("Illinois-Michigan", "Illinois", "Michigan"),
    ("Illinois-Northwestern", "Illinois", "Northwestern"),
    ("Illinois-Ohio State", "Illinois", "Ohio State"),
    ("Illinois-Purdue", "Illinois", "Purdue"),
    ("Indiana-Kentucky", "Indiana", "Kentucky"),
    ("Indiana-Michigan State", "Indiana", "Michigan State"),
    ("Indiana-Purdue", "Indiana", "Purdue"),
    ("Iowa-Iowa State", "Iowa", "Iowa State"),
    ("Iowa-Minnesota", "Iowa", "Minnesota"),
    ("Iowa-Nebraska", "Iowa", "Nebraska"),
    ("Iowa-Wisconsin", "Iowa", "Wisconsin"),
    ("Iowa State-Missouri", "Iowa State", "Missouri"),
    ("Iowa State-Nebraska", "Iowa State", "Nebraska"),
    ("Iron Bowl", "Alabama", "Auburn"),
    ("Kansas-Nebraska", "Kansas", "Nebraska"),
    ("Kansas State-Missouri", "Kansas State", "Missouri"),
    ("Kansas State-Nebraska", "Kansas State", "Nebraska"),
    ("Kansas State-Oklahoma", "Kansas State", "Oklahoma"),
    ("Kentucky-Louisville", "Kentucky", "Louisville"),
    ("Kentucky-Tennessee", "Kentucky", "Tennessee"),
    ("Kentucky-Vanderbilt", "Kentucky", "Vanderbilt"),
    ("Keystone Classic", "Penn State", "Pittsburgh"),
    ("Lone Star Showdown", "Texas", "Texas A&M"),
    ("Louisiana-Louisiana Tech", "Louisiana", "Louisiana Tech"),
    ("Louisiana Tech-Louisiana-Monroe", "Louisiana Tech", "Louisiana-Monroe"),
    ("Louisville-Memphis", "Louisville", "Memphis"),
    ("Louisville-Miami", "Louisville", "Miami"),
    ("LSU-Mississippi State", "LSU", "Mississippi State"),
    ("LSU-Texas A&M", "LSU", "Texas A&M"),
    ("Magnolia Bowl", "LSU", "Ole Miss"),
    ("Maryland-Penn State", "Maryland", "Penn State"),
    ("Maryland-Rutgers", "Maryland", "Rutgers"),
    ("Maryland-Virginia", "Maryland", "Virginia"),
    ("Maryland-West Virginia", "Maryland", "West Virginia"),
    ("Miami-Nebraska", "Miami", "Nebraska"),
    ("Miami-Virginia Tech", "Miami", "Virginia Tech"),
    ("Michigan-Michigan State", "Michigan", "Michigan State"),
    ("Michigan-Minnesota", "Michigan", "Minnesota"),
    ("Michigan-Northwestern", "Michigan", "Northwestern"),
    ("Michigan-Notre Dame", "Michigan", "Notre Dame"),
    ("Michigan-Penn State", "Michigan", "Penn State"),
    ("Michigan State-Notre Dame", "Michigan State", "Notre Dame"),
    ("Mid-South Rivalry", "Memphis", "Ole Miss"),
    ("Minnesota-Nebraska", "Minnesota", "Nebraska"),
    ("Minnesota-Penn State", "Minnesota", "Penn State"),
    ("Minnesota-Wisconsin", "Minnesota", "Wisconsin"),
    ("Missouri-Nebraska", "Missouri", "Nebraska"),
    ("Missouri-Oklahoma", "Missouri", "Oklahoma"),
    ("Missouri-South Carolina", "Missouri", "South Carolina"),
    ("Modern Day Hate", "Georgia Southern", "Georgia State"),
    ("Navy-SMU", "Navy", "SMU"),
    ("Navy-Notre Dame", "Navy", "Notre Dame"),
    ("NC State-Wake Forest", "NC State", "Wake Forest"),
    ("Nebraska-Oklahoma", "Nebraska", "Oklahoma"),
    ("Nebraska-Wisconsin", "Nebraska", "Wisconsin"),
    ("North Carolina-NC State", "North Carolina", "NC State"),
    ("North Carolina-Wake Forest", "North Carolina", "Wake Forest"),
    ("Northwestern-Notre Dame", "Northwestern", "Notre Dame"),
    ("Notre Dame-Pittsburgh", "Notre Dame", "Pittsburgh"),
    ("Notre Dame-Purdue", "Notre Dame", "Purdue"),
    ("Notre Dame-Stanford", "Notre Dame", "Stanford"),
    ("Notre Dame-USC", "Notre Dame", "USC"),
    ("Ohio State-Penn State", "Ohio State", "Penn State"),
    ("Oklahoma State-Tulsa", "Oklahoma State", "Tulsa"),
    ("Ole Miss-Tennessee", "Ole Miss", "Tennessee"),
    ("Ole Miss-Tulane", "Ole Miss", "Tulane"),
    ("Ole Miss-Vanderbilt", "Ole Miss", "Vanderbilt"),
    ("Oregon-Oregon State", "Oregon", "Oregon State"),
    ("Oregon-Stanford", "Oregon", "Stanford"),
    ("Oregon-USC", "Oregon", "USC"),
    ("Oregon-Washington", "Oregon", "Washington"),
    ("Pacific-San José State", "Pacific", "San José State"),
    ("Paint Bucket Bowl", "Arkansas State", "Memphis"),
    ("Palmetto Bowl", "Clemson", "South Carolina"),
    ("Penn State-Syracuse", "Penn State", "Syracuse"),
    ("Penn State-West Virginia", "Penn State", "West Virginia"),
    ("Pittsburgh-Syracuse", "Pittsburgh", "Syracuse"),
    ("Red River Rivalry", "Oklahoma", "Texas"),
    ("Rice-SMU", "Rice", "SMU"),
    ("Rice-Texas", "Rice", "Texas"),
    ("Rio Grande Rivalry", "New Mexico", "New Mexico State"),
    ("Rivalry in Dixie", "Louisiana Tech", "Southern Miss"),
    ("Rocky Mountain Showdown", "Colorado", "Colorado State"),
    ("Royal Rivalry", "James Madison", "Old Dominion"),
    ("Rumble in the Rockies", "Colorado", "Utah"),
    ("Safeway Bowl", "North Texas", "SMU"),
    ("Sam Houston-Texas State", "Sam Houston", "Texas State"),
    ("Sewanee-Vanderbilt", "Sewanee", "Vanderbilt"),
    ("Shula Bowl", "Florida Atlantic", "FIU"),
    ("South's Oldest Rivalry", "North Carolina", "Virginia"),
    ("Stanford-UCLA", "Stanford", "UCLA"),
    ("Stanford-USC", "Stanford", "USC"),
    ("Sunflower Showdown", "Kansas", "Kansas State"),
    ("Syracuse-UConn", "Syracuse", "UConn"),
    ("Syracuse-West Virginia", "Syracuse", "West Virginia"),
    ("TCU-Texas", "TCU", "Texas"),
    ("TCU-Texas A&M", "TCU", "Texas A&M"),
    ("TCU-Texas Tech", "TCU", "Texas Tech"),
    ("Techmo Bowl", "Georgia Tech", "Virginia Tech"),
    ("Tennessee-Vanderbilt", "Tennessee", "Vanderbilt"),
    ("Texas-Texas Tech", "Texas", "Texas Tech"),
    ("Texas A&M-Texas Tech", "Texas A&M", "Texas Tech"),
    ("Textile Bowl", "Clemson", "NC State"),
    ("The Game", "Michigan", "Ohio State"),
    ("The Old Mountain Feud", "Appalachian State", "Marshall"),
    ("Third Saturday in October", "Alabama", "Tennessee"),
    ("Tiger Bowl", "Auburn", "LSU"),
    ("UConn-UMass", "UConn", "UMass"),
    ("UCLA-USC", "UCLA", "USC"),
    ("Virginia Tech-West Virginia", "Virginia Tech", "West Virginia"),
    ("Virginia-Virginia Tech", "Virginia", "Virginia Tech"),
    ("War on I-4", "South Florida", "UCF"),
]
