"""
Read-only comparison: does refitting Model C on correctly-paired
(pre-snap score) situational data actually predict better than the
currently-shipped src/wp_situational.py, which was fit on data with the
score/situation pairing bug described in src/espn.py's 2026-08-31 fix
(commit 8815ce7)? Produces no file changes -- src/wp_situational.py is
only regenerated by scripts/build_wp_situational_module.py, and only
after this comparison is reviewed.

Methodology: an 80/20 GAME-level split (never by play -- avoids same-game
leakage between train/test), the same split used for both variants so any
difference is attributable to the pairing fix, not split luck. Two
training sets are built from the SAME plays:
  - OLD: down/distance paired with that play's own (already-updated,
    buggy) post-play score -- replicates what build_wp_situational_module.py
    did before this fix.
  - NEW: down/distance paired with the score as of the snap, via
    espn.extract_situational_plays() (the shared, now-fixed extractor).
Both variants are fit (statsmodels Logit) on the TRAIN split only. Both
are then evaluated on the SAME held-out test set, built the NEW
(correctly-paired) way -- because that's what every real caller feeds the
model now that src/espn.py is fixed, regardless of which model is
running. This isolates exactly the question that matters for the swap
decision: given real (fixed) inputs, does the model trained on fixed data
outperform the one trained on buggy data?

Usage:
    venv/bin/python3 scripts/compare_wp_pairing_refit.py [path/to/cfb.db]
"""
import sys

import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.stats import rankdata

sys.path.insert(0, ".")

from src import db, espn
from src.espn import _parse_clock

EPS = 1e-4
MAX_DISTANCE = 30
SEED = 20260901


def logit(p):
    p = np.clip(p, EPS, 1 - EPS)
    return np.log(p / (1 - p))


def _iter_drives(raw):
    drives = raw.get("drives", {})
    out = list(drives.get("previous", []))
    current = drives.get("current")
    if isinstance(current, dict):
        out.append(current)
    elif isinstance(current, list):
        out.extend(current)
    return out


def _old_buggy_rows(raw, home_team_id):
    """Replicates build_wp_situational_module.py's dataset builder AS IT
    WAS before the pairing fix -- down/distance paired with that same
    play's own (post-play) homeScore/awayScore. Kept here, isolated, only
    so this comparison can reconstruct "what would we have shipped" --
    not used anywhere else."""
    out = []
    for drive in _iter_drives(raw):
        off_team = str(drive.get("team", {}).get("id", ""))
        if not off_team:
            continue
        off_is_home = off_team == home_team_id

        for play in drive.get("plays", []):
            period = (play.get("period") or {}).get("number")
            if period is None or period > 4:
                continue

            start = play.get("start", {})
            down = start.get("down")
            distance = start.get("distance")
            yards_to_go = start.get("yardsToEndzone")
            if down is None or distance is None or yards_to_go is None:
                continue
            if not (1 <= down <= 4) or not (0 < yards_to_go <= 100) or distance < 0:
                continue

            home_score = play.get("homeScore")
            away_score = play.get("awayScore")
            if home_score is None or away_score is None:
                continue

            secs_remaining = _parse_clock((play.get("clock") or {}).get("displayValue") or "")
            if secs_remaining is None:
                continue
            elapsed_seconds = (period - 1) * 900 + (900 - secs_remaining)

            out.append({
                "elapsed_seconds": elapsed_seconds,
                "off_is_home": off_is_home,
                "down": down,
                "distance": distance,
                "yards_to_go": yards_to_go,
                "goal_to_go": int(distance >= yards_to_go),
                "home_score": home_score,
                "away_score": away_score,
            })
    return out


def _rows_from_plays(plays, game, home_won, skip_synthetic):
    rows = []
    for play in plays:
        if skip_synthetic and not play.get("play_id", "x"):
            continue
        off_is_home = play["off_is_home"]
        offense_score = play["home_score"] if off_is_home else play["away_score"]
        defense_score = play["away_score"] if off_is_home else play["home_score"]
        offense_pregame_wp = game["initial_home_wp"] if off_is_home else 1 - game["initial_home_wp"]
        offense_won = home_won if off_is_home else 1 - home_won
        seconds_remaining_reg = max(0, 3600 - play["elapsed_seconds"])
        rows.append({
            "game_id": game["game_id"],
            "down": play["down"],
            "distance": min(play["distance"], MAX_DISTANCE),
            "yards_to_go": play["yards_to_go"],
            "goal_to_go": play["goal_to_go"],
            "score_diff": offense_score - defense_score,
            "seconds_remaining_reg": seconds_remaining_reg,
            "offense_pregame_wp": offense_pregame_wp,
            "offense_won": offense_won,
        })
    return rows


def build_both_datasets(conn):
    games = conn.execute("""
        SELECT game_id, home_team_id, home_score, away_score, initial_home_wp
        FROM games
        WHERE completed = 1 AND detail_fetched = 1
          AND home_score IS NOT NULL AND away_score IS NOT NULL
          AND home_score != away_score
          AND initial_home_wp IS NOT NULL
    """).fetchall()

    old_rows, new_rows = [], []
    n_games_used = 0
    for g in games:
        raw = db.get_game_raw_json(conn, g["game_id"])
        if not raw:
            continue
        n_games_used += 1
        home_won = 1 if g["home_score"] > g["away_score"] else 0

        old_plays = _old_buggy_rows(raw, g["home_team_id"])
        old_rows.extend(_rows_from_plays(old_plays, g, home_won, skip_synthetic=False))

        new_plays = espn.extract_situational_plays(raw, g["home_team_id"])
        new_rows.extend(_rows_from_plays(new_plays, g, home_won, skip_synthetic=True))

    return pd.DataFrame(old_rows), pd.DataFrame(new_rows), n_games_used, len(games)


def make_design(df):
    time_frac = df["seconds_remaining_reg"] / 3600.0
    urgency = df["score_diff"] * (1 - time_frac)
    X = pd.DataFrame({
        "logit_offense_pregame_wp": logit(df["offense_pregame_wp"].to_numpy()),
        "score_diff": df["score_diff"],
        "time_remaining_frac": time_frac,
        "urgency": urgency,
        "down2": (df["down"] == 2).astype(int),
        "down3": (df["down"] == 3).astype(int),
        "down4": (df["down"] == 4).astype(int),
        "distance": df["distance"],
        "yards_to_go": df["yards_to_go"],
        "goal_to_go": df["goal_to_go"],
    })
    return sm.add_constant(X, has_constant="add")


def fit(df):
    X = make_design(df)
    y = df["offense_won"]
    return sm.Logit(y, X).fit(disp=0, maxiter=100)


def _brier(pred, outcome):
    return float(np.mean((pred - outcome) ** 2))


def _log_loss(pred, outcome):
    p = np.clip(pred, EPS, 1 - EPS)
    return float(-np.mean(outcome * np.log(p) + (1 - outcome) * np.log(1 - p)))


def _auc(pred, outcome):
    """Mann-Whitney-U rank AUC -- same formula as scripts/model_c_layman_metrics.py,
    no sklearn dependency (matches this repo's existing convention)."""
    ranks = rankdata(pred)
    n_pos = int(outcome.sum())
    n_neg = len(outcome) - n_pos
    if n_pos == 0 or n_neg == 0:
        return float("nan")
    sum_ranks_pos = ranks[outcome == 1].sum()
    return float((sum_ranks_pos - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg))


def evaluate(model, df, label):
    X = make_design(df)
    y_true = df["offense_won"].to_numpy()
    y_pred = model.predict(X).to_numpy()
    brier = _brier(y_pred, y_true)
    ll = _log_loss(y_pred, y_true)
    acc = float(((y_pred >= 0.5).astype(int) == y_true).mean())
    auc = _auc(y_pred, y_true)
    print(f"  {label:<32} Brier={brier:.4f}  log-loss={ll:.4f}  accuracy={acc:.4f}  AUC={auc:.4f}  n={len(df)}")
    return {"label": label, "brier": brier, "log_loss": ll, "accuracy": acc, "auc": auc, "n": len(df)}


def main():
    db_path = sys.argv[1] if len(sys.argv) > 1 else None
    conn = db.get_connection(db_path)

    print("Building OLD (buggy pairing) and NEW (fixed pairing) datasets from the same games...")
    old_df, new_df, n_games_used, n_games_total = build_both_datasets(conn)
    print(f"Games with raw JSON available: {n_games_used}/{n_games_total}")
    print(f"OLD dataset rows: {len(old_df)}   NEW dataset rows: {len(new_df)} "
          f"(NEW is smaller by design -- synthetic closing entries excluded)\n")

    rng = np.random.default_rng(SEED)
    game_ids = old_df["game_id"].unique()
    rng.shuffle(game_ids)
    n_test_games = int(len(game_ids) * 0.2)
    test_games = set(game_ids[:n_test_games])
    train_games = set(game_ids[n_test_games:])
    print(f"Game-level 80/20 split: {len(train_games)} train games, {len(test_games)} test games\n")

    old_train = old_df[old_df["game_id"].isin(train_games)]
    new_train = new_df[new_df["game_id"].isin(train_games)]
    new_test = new_df[new_df["game_id"].isin(test_games)]

    print(f"Fitting OLD-style model on {len(old_train)} buggy-paired train rows...")
    old_model = fit(old_train)
    print(f"Fitting NEW-style model on {len(new_train)} correctly-paired train rows...")
    new_model = fit(new_train)

    print("\nCoefficients (OLD vs NEW, train-split fits -- for reference; the shipped module is fit on the FULL corpus):")
    param_names = ["const", "logit_offense_pregame_wp", "score_diff", "time_remaining_frac",
                   "urgency", "down2", "down3", "down4", "distance", "yards_to_go", "goal_to_go"]
    for name in param_names:
        print(f"  {name:<28} old={old_model.params[name]:+.4f}   new={new_model.params[name]:+.4f}")

    print(f"\nEvaluating both models on the SAME held-out test set ({len(new_test)} rows, "
          f"correctly-paired -- this is what real inference feeds either model, "
          f"now that src/espn.py's extractor is fixed):")
    results = []
    results.append(evaluate(old_model, new_test, "OLD model (trained on buggy data)"))
    results.append(evaluate(new_model, new_test, "NEW model (trained on fixed data)"))

    print("\nFor reference -- OLD model evaluated on OLD-style (buggy) held-out rows, i.e. its own "
          "internally-consistent picture before this investigation existed:")
    old_test_selfconsistent = old_df[old_df["game_id"].isin(test_games)]
    evaluate(old_model, old_test_selfconsistent, "OLD model on OLD-style test rows")

    delta_brier = results[0]["brier"] - results[1]["brier"]
    print(f"\nBrier score delta (OLD - NEW) on the shared fixed-pairing test set: {delta_brier:+.4f} "
          f"({'NEW is better' if delta_brier > 0 else 'OLD is better' if delta_brier < 0 else 'tied'})")


if __name__ == "__main__":
    main()
