"""
Read-only comparison: does excluding OT-bound games from Model C's
TRAINING set change anything? Rationale (user's, 2026-09-01): a play from
the 3rd quarter of a game that later ties and goes to overtime carries a
target label (offense_won) partly decided by OT's own near-coinflip
resolution -- information no regulation-era feature can predict -- so
including those games' regulation plays in training may just inject label
noise, concentrated in exactly the close/late-game region comeback_erosion
cares about most. Produces no file changes; src/wp_situational.py is only
regenerated by scripts/build_wp_situational_module.py.

Methodology: same as compare_wp_pairing_refit.py -- one game-level 80/20
split, applied to both variants so any difference is attributable to the
OT-exclusion, not split luck. Both training sets use the current (fixed)
pairing + no goal_to_go. Evaluated on the SAME held-out test set, but
TWICE: once restricted to non-OT games only (clean labels, matching what
the training-side argument is actually about) and once on the full
(OT-games-included) test split (matching what the model faces in
production, since every regulation-era READ still needs scoring even for
a game that happens to end in OT).

Usage:
    venv/bin/python3 scripts/compare_wp_ot_exclusion.py [path/to/cfb.db]
"""
import sys

import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.stats import rankdata

sys.path.insert(0, ".")
sys.path.insert(0, "scripts")

from src import db, espn
import build_wp_situational_module as b

SEED = 20260901


def games_with_ot_flag(conn):
    rows = conn.execute("""
        SELECT g.game_id, g.home_team_id, g.home_score, g.away_score, g.initial_home_wp,
               EXISTS(SELECT 1 FROM win_probability wp
                      WHERE wp.game_id = g.game_id AND wp.period_number > 4) AS is_ot
        FROM games g
        WHERE completed = 1 AND detail_fetched = 1
          AND home_score IS NOT NULL AND away_score IS NOT NULL
          AND home_score != away_score
          AND initial_home_wp IS NOT NULL
    """).fetchall()
    return rows


def build_rows(conn, games):
    rows = []
    n_used = 0
    for g in games:
        raw = db.get_game_raw_json(conn, g["game_id"])
        if not raw:
            continue
        n_used += 1
        home_won = 1 if g["home_score"] > g["away_score"] else 0
        for play in espn.extract_situational_plays(raw, g["home_team_id"]):
            if not play["play_id"]:
                continue
            off_is_home = play["off_is_home"]
            offense_score = play["home_score"] if off_is_home else play["away_score"]
            defense_score = play["away_score"] if off_is_home else play["home_score"]
            offense_pregame_wp = g["initial_home_wp"] if off_is_home else 1 - g["initial_home_wp"]
            offense_won = home_won if off_is_home else 1 - home_won
            seconds_remaining_reg = max(0, 3600 - play["elapsed_seconds"])
            rows.append({
                "game_id": g["game_id"],
                "is_ot": g["is_ot"],
                "down": play["down"],
                "distance": min(play["distance"], b.MAX_DISTANCE),
                "yards_to_go": play["yards_to_go"],
                "score_diff": offense_score - defense_score,
                "seconds_remaining_reg": seconds_remaining_reg,
                "offense_pregame_wp": offense_pregame_wp,
                "offense_won": offense_won,
            })
    return pd.DataFrame(rows), n_used


def fit(df):
    X = b.make_design(df)
    y = df["offense_won"]
    return sm.Logit(y, X).fit(disp=0, maxiter=100)


def _brier(pred, outcome):
    return float(np.mean((pred - outcome) ** 2))


def _log_loss(pred, outcome):
    p = np.clip(pred, 1e-4, 1 - 1e-4)
    return float(-np.mean(outcome * np.log(p) + (1 - outcome) * np.log(1 - p)))


def _auc(pred, outcome):
    ranks = rankdata(pred)
    n_pos = int(outcome.sum())
    n_neg = len(outcome) - n_pos
    if n_pos == 0 or n_neg == 0:
        return float("nan")
    sum_ranks_pos = ranks[outcome == 1].sum()
    return float((sum_ranks_pos - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg))


def evaluate(model, df, label):
    X = b.make_design(df)
    y_true = df["offense_won"].to_numpy()
    y_pred = model.predict(X).to_numpy()
    brier = _brier(y_pred, y_true)
    ll = _log_loss(y_pred, y_true)
    acc = float(((y_pred >= 0.5).astype(int) == y_true).mean())
    auc = _auc(y_pred, y_true)
    print(f"  {label:<40} Brier={brier:.4f}  log-loss={ll:.4f}  accuracy={acc:.4f}  AUC={auc:.4f}  n={len(df)}")


def main():
    db_path = sys.argv[1] if len(sys.argv) > 1 else None
    conn = db.get_connection(db_path)

    games = games_with_ot_flag(conn)
    df, n_used = build_rows(conn, games)
    n_ot_games = df[df["is_ot"] == 1]["game_id"].nunique()
    n_total_games = df["game_id"].nunique()
    print(f"Games used: {n_used}   OT games among them: {n_ot_games} ({n_ot_games/n_total_games:.1%})")
    print(f"Total rows: {len(df)}   OT-game rows: {(df['is_ot']==1).sum()} "
          f"({(df['is_ot']==1).sum()/len(df):.1%})\n")

    rng = np.random.default_rng(SEED)
    game_ids = df["game_id"].unique()
    rng.shuffle(game_ids)
    n_test_games = int(len(game_ids) * 0.2)
    test_games = set(game_ids[:n_test_games])
    train_games_all = set(game_ids[n_test_games:])

    test_df_all = df[df["game_id"].isin(test_games)]
    test_df_nonot = test_df_all[test_df_all["is_ot"] == 0]

    train_all = df[df["game_id"].isin(train_games_all)]
    train_nonot = train_all[train_all["is_ot"] == 0]

    print(f"Train rows: ALL-games={len(train_all)}   NON-OT-only={len(train_nonot)} "
          f"(-{len(train_all)-len(train_nonot)} rows, {1 - len(train_nonot)/len(train_all):.1%} smaller)")
    print(f"Test rows:  full={len(test_df_all)}   non-OT-only={len(test_df_nonot)}\n")

    print("Fitting model on ALL games (current approach)...")
    model_all = fit(train_all)
    print("Fitting model on NON-OT games only...")
    model_nonot = fit(train_nonot)

    param_names = ["const", "logit_offense_pregame_wp", "score_diff", "time_remaining_frac",
                   "urgency", "down2", "down3", "down4", "distance", "yards_to_go"]
    print("\nCoefficients (ALL-games vs NON-OT-only train):")
    for name in param_names:
        print(f"  {name:<28} all={model_all.params[name]:+.4f}   non-ot={model_nonot.params[name]:+.4f}")

    print(f"\nEvaluated on the non-OT-only slice of the held-out test set ({len(test_df_nonot)} rows) --"
          f" clean labels, matching what the training-side argument is about:")
    evaluate(model_all, test_df_nonot, "Model trained on ALL games")
    evaluate(model_nonot, test_df_nonot, "Model trained on NON-OT games only")

    print(f"\nEvaluated on the FULL held-out test set ({len(test_df_all)} rows, OT games included) --"
          f" matching real production traffic, since every regulation play still needs scoring"
          f" regardless of how its game eventually ends:")
    evaluate(model_all, test_df_all, "Model trained on ALL games")
    evaluate(model_nonot, test_df_all, "Model trained on NON-OT games only")


if __name__ == "__main__":
    main()
