"""
AUTO-GENERATED by scripts/fit_wp_quarter_model.py on 2026-08-16 --
do not hand-edit. Re-run that script (after pulling more seasons, etc.)
to regenerate this file; it always overwrites, not patches.

Fitted on 1828 completed games, seasons 2024-2025.

Model: logit(wp_at_quarter_end) ~ logit(initial_home_wp) + score_diff,
fit separately per quarter via OLS. Log-odds space reproduces the
empirical fact that a fixed score margin means much less to a heavy
pregame favorite's win probability than to a coinflip game's -- see the
fitting script's docstring for the full rationale.

predict_wp() / wp_residual() are quarter-checkpoint entry points.
predict_wp_elapsed() / coinflip_wp_elapsed() are the continuous-time
counterparts (accept elapsed_seconds directly instead of a quarter
bucket) -- the intended entry points for a comeback-detection metric
that needs a value at every score-change event, not just quarter ends.
Both families agree closely within Q1-3; predict_wp_elapsed() is the
only one of the two defined (via extrapolation) past that range.
"""
import math

QUARTER_MODELS = {
    1: {"const": -0.0013878107881984414, "b_logit_initial_wp": 0.7758191817418458, "b_score_diff": 0.11332943574510039, "r_squared": 0.9781318353834182, "n": 1828},
    2: {"const": 0.010168388432078743, "b_logit_initial_wp": 0.4987718002830629, "b_score_diff": 0.14658237441871205, "r_squared": 0.9762658347106806, "n": 1828},
    3: {"const": 0.0018355942281254069, "b_logit_initial_wp": 0.1925299372656008, "b_score_diff": 0.1866788057984508, "r_squared": 0.9137881235352493, "n": 1828},
}

ELAPSED_MODEL = {
    "const": 0.007327248841122004, "b_logit_initial_wp": 0.9964299627340012, "b_score_diff": 0.0887354471855863,
    "b_elapsed": -0.007819885198732073, "b_elapsed2": 0.0018918514423067342,
    "b_sd_elapsed": 0.018962285372763798, "b_sd_elapsed2": 0.004555394866436478,
    "b_init_elapsed": -0.18699484227188348, "b_init_elapsed2": -0.026153767360550403,
    "r_squared": 0.9610573606954762, "n": 239266,
}


def logit(p):
    p = min(max(p, 1e-4), 1 - 1e-4)
    return math.log(p / (1 - p))


def inv_logit(x):
    return 1 / (1 + math.exp(-x))


def predict_wp(quarter, initial_home_wp, score_diff):
    """Model-predicted home_win_pct at the end of `quarter` (1, 2, or 3),
    given the pregame line and the score at that point. Raises KeyError
    for quarters outside the fitted range (only Q1-Q3 currently)."""
    m = QUARTER_MODELS[quarter]
    l_pred = m["const"] + m["b_logit_initial_wp"] * logit(initial_home_wp) + m["b_score_diff"] * score_diff
    return inv_logit(l_pred)


def coinflip_wp(quarter, score_diff):
    """predict_wp() with the pregame line forced to a 50/50 coin flip --
    i.e. what this score_diff alone implies about win probability, with the
    pregame-favorite skew factored out entirely. This is the anchor-free
    scale a comeback should be measured against: a "true" comeback is one
    where THIS quantity swings a lot, not just the raw (anchor-skewed) WP."""
    return predict_wp(quarter, 0.5, score_diff)


def wp_residual(quarter, initial_home_wp, score_diff, actual_home_wp):
    """actual - predicted, in probability space. Positive means the home
    team is doing better than the anchor+score model expects; negative
    means worse. Near zero means this WP value is unremarkable once the
    pregame line and actual score are accounted for -- e.g. a heavy
    favorite's high WP off a modest lead residuals near zero, rather than
    reading as a dramatic swing the way raw WP would."""
    return actual_home_wp - predict_wp(quarter, initial_home_wp, score_diff)


def predict_wp_elapsed(elapsed_seconds, initial_home_wp, score_diff):
    """Continuous-time counterpart to predict_wp() -- quadratic-in-elapsed
    interactions instead of a discrete quarter bucket. Fit on Q1-3 data
    only (elapsed 0-2700s); called on a Q4/OT elapsed value extrapolates
    past that range on purpose (accepted, not independently verified --
    see the fitting script's docstring)."""
    m = ELAPSED_MODEL
    eq = elapsed_seconds / 900.0
    li = logit(initial_home_wp)
    l_pred = (m["const"] + m["b_logit_initial_wp"] * li + m["b_score_diff"] * score_diff
              + m["b_elapsed"] * eq + m["b_elapsed2"] * eq ** 2
              + m["b_sd_elapsed"] * score_diff * eq + m["b_sd_elapsed2"] * score_diff * eq ** 2
              + m["b_init_elapsed"] * li * eq + m["b_init_elapsed2"] * li * eq ** 2)
    return inv_logit(l_pred)


def coinflip_wp_elapsed(elapsed_seconds, score_diff):
    """predict_wp_elapsed() with the pregame line forced to a coin flip --
    continuous-time analogue of coinflip_wp()."""
    return predict_wp_elapsed(elapsed_seconds, 0.5, score_diff)
