"""
AUTO-GENERATED by scripts/build_wp_situational_module.py on 2026-09-02 --
do not hand-edit. Re-run that script (after pulling more seasons, etc.) to
regenerate this file; it always overwrites, not patches.

Fitted on 3449 completed games, regulation plays only (period 1-4,
528617 scrimmage-down plays) -- OT is deliberately excluded from both
training and the intended use of this module (see the fitting script's
docstring). Offense-perspective logistic regression (target = actual game
outcome, not ESPN's own WP) -- McFadden pseudo-R^2=0.5190.

Endgame urgency runs on a DISCRETE scores_needed count (see
scores_needed()'s own docstring), not the raw continuous score_diff --
football only scores in fixed increments (FG=3, TD=6/7/8), so a 1-point
and 2-point deficit are functionally identical and a continuous term
spreading them apart was underselling how safe a narrow late lead really
is (see scripts/compare_wp_endgame_calibration.py and
scripts/validate_endgame_lead_win_rate.py for the full investigation and
held-out validation).

predict_wp_offense()/coinflip_wp_offense() take the offense's own down/
distance/field position plus score/time/pregame WP and return the win
probability for the team CURRENTLY ON OFFENSE. Callers needing a
home-perspective value must flip the result based on which team has the
ball -- see src/scoring.py's comeback_erosion for the wrapper that does
this.
"""
import math

MODEL = {
    "const": 1.316898491950799,
    "b_logit_offense_pregame_wp": 0.7990132554278359,
    "b_score_diff": 0.13807377176149227,
    "b_time_remaining_frac": -1.263217042478765,
    "b_down2": -0.08875115012568387,
    "b_down3": -0.20496958297361362,
    "b_down4": -0.38411864074961194,
    "b_distance": -0.011346235375379302,
    "b_yards_to_go": -0.009351649686584326,
    "b_sn_urgency": -0.36752746673283976,
    "b_sn_urgency3": 1.3966167964176304,
    "b_sn_time_remaining_frac2": 0.8776342329690779,
    "b_sn_inv_sqrt_urgency": 2.318340401941777,
}


def logit(p):
    p = min(max(p, 1e-4), 1 - 1e-4)
    return math.log(p / (1 - p))


def inv_logit(x):
    return 1 / (1 + math.exp(-x))


def scores_needed(score_diff):
    """Signed 'possessions needed' -- see build_wp_situational_module.py's
    identical helper for the full rationale. Any deficit of 1-8 (up to a
    single TD+2pt) maps to "1 score", 9-16 to "2 scores", etc.; sign
    preserved so a trailing offense reads negative."""
    if score_diff == 0:
        return 0
    return math.copysign(math.ceil(abs(score_diff) / 8.0), score_diff)


def predict_wp_offense(*, down, distance, yards_to_go,
                        score_diff, elapsed_seconds, offense_pregame_wp):
    """Win probability for the team on offense, given their own down/
    distance/field position, the score (offense - defense), elapsed game
    seconds (0-3600, regulation only -- do not call this for OT plays),
    and their own pregame win probability."""
    m = MODEL
    time_remaining_frac = max(0.0, 3600 - elapsed_seconds) / 3600.0
    sn = scores_needed(score_diff)
    l_pred = (m["const"]
              + m["b_logit_offense_pregame_wp"] * logit(offense_pregame_wp)
              + m["b_score_diff"] * score_diff
              + m["b_time_remaining_frac"] * time_remaining_frac
              + m["b_down2"] * (1 if down == 2 else 0)
              + m["b_down3"] * (1 if down == 3 else 0)
              + m["b_down4"] * (1 if down == 4 else 0)
              + m["b_distance"] * min(distance, 30)
              + m["b_yards_to_go"] * yards_to_go
              + m["b_sn_urgency"] * sn * (1 - time_remaining_frac)
              + m["b_sn_urgency3"] * sn * (1 - time_remaining_frac) ** 3
              + m["b_sn_time_remaining_frac2"] * time_remaining_frac ** 2
              + m["b_sn_inv_sqrt_urgency"] * sn / math.sqrt(max(0.0, 3600 - elapsed_seconds) + 5.0))
    return inv_logit(l_pred)


def coinflip_wp_offense(*, down, distance, yards_to_go,
                         score_diff, elapsed_seconds):
    """predict_wp_offense() with the offense's own pregame WP forced to a
    50/50 coin flip -- the anchor-free scale to judge an in-game swing
    against, same rationale as wp_baseline.coinflip_wp_elapsed()."""
    return predict_wp_offense(
        down=down, distance=distance, yards_to_go=yards_to_go,
        score_diff=score_diff, elapsed_seconds=elapsed_seconds, offense_pregame_wp=0.5,
    )
