"""
AUTO-GENERATED by scripts/build_wp_situational_module.py on 2026-08-30 --
do not hand-edit. Re-run that script (after pulling more seasons, etc.) to
regenerate this file; it always overwrites, not patches.

Fitted on 3449 completed games, regulation plays only (period 1-4,
580883 scrimmage-down plays) -- OT is deliberately excluded from both
training and the intended use of this module (see the fitting script's
docstring). Offense-perspective logistic regression (target = actual game
outcome, not ESPN's own WP) -- McFadden pseudo-R^2=0.5192.

predict_wp_offense()/coinflip_wp_offense() take the offense's own down/
distance/field position plus score/time/pregame WP and return the win
probability for the team CURRENTLY ON OFFENSE. Callers needing a
home-perspective value must flip the result based on which team has the
ball -- see src/scoring.py's comeback_erosion for the wrapper that does
this.
"""
import math

MODEL = {
    "const": 1.1099742687889258,
    "b_logit_offense_pregame_wp": 0.7972313735417178,
    "b_score_diff": 0.06049179479305411,
    "b_time_remaining_frac": -0.32467680373205055,
    "b_urgency": 0.21824273966762975,
    "b_down2": -0.06940103866903506,
    "b_down3": -0.1825414317089864,
    "b_down4": -0.3550788726186753,
    "b_distance": -0.011922454168318525,
    "b_yards_to_go": -0.009476447910007096,
}


def logit(p):
    p = min(max(p, 1e-4), 1 - 1e-4)
    return math.log(p / (1 - p))


def inv_logit(x):
    return 1 / (1 + math.exp(-x))


def predict_wp_offense(*, down, distance, yards_to_go,
                        score_diff, elapsed_seconds, offense_pregame_wp):
    """Win probability for the team on offense, given their own down/
    distance/field position, the score (offense - defense), elapsed game
    seconds (0-3600, regulation only -- do not call this for OT plays),
    and their own pregame win probability."""
    m = MODEL
    time_remaining_frac = max(0.0, 3600 - elapsed_seconds) / 3600.0
    urgency = score_diff * (1 - time_remaining_frac)
    l_pred = (m["const"]
              + m["b_logit_offense_pregame_wp"] * logit(offense_pregame_wp)
              + m["b_score_diff"] * score_diff
              + m["b_time_remaining_frac"] * time_remaining_frac
              + m["b_urgency"] * urgency
              + m["b_down2"] * (1 if down == 2 else 0)
              + m["b_down3"] * (1 if down == 3 else 0)
              + m["b_down4"] * (1 if down == 4 else 0)
              + m["b_distance"] * min(distance, 30)
              + m["b_yards_to_go"] * yards_to_go)
    return inv_logit(l_pred)


def coinflip_wp_offense(*, down, distance, yards_to_go,
                         score_diff, elapsed_seconds):
    """predict_wp_offense() with the offense's own pregame WP forced to a
    50/50 coin flip -- the anchor-free scale to judge an in-game swing
    against, same rationale as wp_baseline.coinflip_wp_elapsed()."""
    return predict_wp_offense(
        down=down, distance=distance, yards_to_go=yards_to_go,
        score_diff=score_diff, elapsed_seconds=elapsed_seconds, offense_pregame_wp=0.5,
    )
